---
- hosts: localhost
  tasks:
  - name: launch instance
    os_server: 
      state: present
      auth: 
        auth_url: https://keystone.rc.nectar.org.au:5000/v2.0/
        username: {{ user }}
        password: {{ pass }}
        project_name: TouchFrame